baseURL = "https://hkvision.cn"
languageCode = "zh-CN"
title = "HaoKunT的博客"
theme = "maupassant"
summaryLength = 10
# googleAnalytics = "UA-144740297-1"

[author]
  name = "HaoKunT"

[params]
  author = "HaoKunT"
  subtitle = "GIS学生党，喜欢学习新技术"
  keywords = "GIS,golang,go语言,python,HaoKunT,R,blog,博客"
  description = "数据库,Web后端,Django,Golang,GIS"
  busuanzi = true
  preserveTaxonomyNames = true
  disablePathToLower = true
  localSearch = true

  fancybox = true

  # customJS = ["baidu-push.js"]
  
  [params.utteranc]
    enable = true
    repo = "HaoKunT/blog-hugo-comments"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

  [[params.links]]
    title = "R语言空间数据处理与分析实践教程"
    name = "R语言空间数据处理与分析实践教程"
    url = "https://baike.baidu.com/item/R%E8%AF%AD%E8%A8%80%E7%A9%BA%E9%97%B4%E6%95%B0%E6%8D%AE%E5%A4%84%E7%90%86%E4%B8%8E%E5%88%86%E6%9E%90%E5%AE%9E%E8%B7%B5%E6%95%99%E7%A8%8B"

  [[params.links]]
    title = "CS-Tao的博客"
    name = "CS-Tao的博客"
    url = "https://home.cs-tao.cc"

  [[params.links]]
    title = "HPdell的博客"
    name = "HPdell的博客"
    url = "https://hpdell.github.io"

  [[params.links]]
    title = "lsq的博客"
    name = "lsq的博客"
    url = "https://lsq210.github.io"

  [[params.links]]
    title = "mysticfalls的博客"
    name = "mysticfalls的博客"
    url = "https://mysticfalls0709.github.io"

  [[params.links]]
    title = "GWmodel Lab团队主页"
    name = "GWmodel Lab团队主页"
    url = "http://gwmodel.whu.edu.cn"

  [[params.ads]]
    title = "【云小站】新老顾客都返佣"
    url = "https://www.aliyun.com/minisite/goods?source=5176.11533457&userCode=lxdp38ei"
    img = "https://img.alicdn.com/tfs/TB1iSEKqRr0gK0jSZFnXXbRRXXa-220-120.jpg"

  [[params.ads]]
    title = "采购季，上云仅233元/3年"
    url = "https://www.aliyun.com/sale-season/2020/procurement-new-members?source=5176.11533457&userCode=lxdp38ei&type=copy"
    img = "https://img.alicdn.com/tfs/TB1Yr3IvubviK0jSZFNXXaApXXa-220-120.jpg"

  [[params.ads]]
    title = "企业级云服务器 1折特惠"
    url = "https://promotion.aliyun.com/ntms/act/enterprise-discount.html?source=5176.11533457&userCode=lxdp38ei&type=copy"
    img = "https://img.alicdn.com/tfs/TB1Gc3zmAL0gK0jSZFxXXXWHVXa-259-194.jpg"

[menu]

  [[menu.main]]
    identifier = "tools"
    name = "工具"
    url = "/tools/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
  
[permalinks]
  post = "/:year/:month/:day/:title/"

[markup]
  [markup.highlight]
    lineNos = true
    style = "rainbow_dash"

